import Image from "next/image";

export default function Home() {
  return (
    <main className="flex flex-col items-center justify-between min-h-screen my_border my_container ">

      Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sunt vero pariatur facilis, debitis neque quam maxime aut odit harum labore consequuntur vitae ut quis. Minima hic optio dolores nisi labore.
      Nostrum architecto ea minus officia vero sunt ipsam, atque unde, ab quae dolor ut eligendi, error ullam expedita eius? Deserunt delectus adipisci distinctio, aspernatur et sunt? Facilis velit dolorem libero.
      Odit iure id porro nam. Ea fuga repellat in, fugiat vel quod nesciunt maiores consequatur, expedita, maxime impedit unde temporibus. Expedita quisquam veritatis repellendus nemo quis facilis. Nam, nemo excepturi!
      At ratione porro ullam soluta, culpa similique aspernatur nesciunt vel ab libero laborum doloremque. Beatae earum obcaecati sint illo ut, veritatis, provident officia distinctio fugiat non repellendus, quidem mollitia atque.
      Beatae maxime corporis corrupti omnis culpa nam consequuntur facilis excepturi quod! Necessitatibus facilis illo eligendi placeat, nihil fuga, in facere accusamus magnam ea tempora eum impedit amet molestiae vel! Recusandae!
      Ipsam rem suscipit nulla qui! Beatae placeat cum provident debitis dolore, pariatur accusantium labore doloribus inventore natus odio minus, ut dolorum doloremque vitae maiores ex deserunt distinctio praesentium fugiat! Aspernatur?
      Dolores alias doloribus quia debitis ea deleniti cupiditate aut unde provident fuga ab saepe iure corporis consectetur, nihil incidunt nulla quod animi magni velit. Iusto provident totam ratione sed corrupti.
      A vero recusandae, deserunt quam magnam, saepe voluptatibus voluptates veniam error, quae nostrum iste laudantium doloremque unde voluptate voluptas eligendi molestiae dolore corporis perferendis! Asperiores numquam exercitationem saepe ducimus nobis.
      Voluptates architecto officiis est natus nobis, nam rem dolor? Architecto dolores pariatur accusamus magni, voluptate expedita dignissimos. Magnam sint eum dolor quaerat? Quisquam ab doloribus sint laudantium, mollitia temporibus quidem.
      Cupiditate veniam, officiis odit, tempora hic perferendis numquam rem doloribus pariatur autem, placeat maiores repudiandae. Doloremque ab quo magnam molestias eos distinctio! Deleniti omnis molestiae eaque saepe, eius incidunt illo?
      Suscipit maxime distinctio voluptas quasi corporis nulla cum, eligendi quisquam voluptates nam doloribus quas ab, eum molestias ducimus cumque, dicta delectus iste laboriosam unde tempore quam officia veritatis! Fugiat, ea.
      At vel odit tempore. Architecto adipisci aut tenetur. Dolores natus debitis aliquid perferendis quae expedita ex veritatis reprehenderit hic, consequuntur harum quaerat velit alias corrupti. Nesciunt pariatur quibusdam at natus!
      Amet, quam? Cum animi tenetur dolore sed voluptas. Iste dolorem eos consequatur, in quibusdam maiores optio atque mollitia modi distinctio molestias aperiam nulla natus ad laboriosam error, quis et sequi!
      Inventore vel tenetur ratione doloribus porro, ad cum voluptas culpa cumque totam odit similique animi, earum voluptatem quis facilis provident harum pariatur non dolores fugiat neque optio? Maiores, excepturi laborum.
      Quod est unde sed? Voluptate saepe hic placeat incidunt cupiditate exercitationem error accusantium veritatis, repellat natus asperiores eum eaque corrupti soluta itaque quis pariatur aut nam porro! Repellendus, ex architecto.
      Reprehenderit necessitatibus possimus, qui nesciunt assumenda cumque porro placeat numquam ullam unde quas ab quisquam, laboriosam sequi saepe ipsa, accusamus dolores cum vel adipisci provident optio. Ad deserunt mollitia doloremque!
      Ducimus totam necessitatibus, tenetur eius in, magnam eaque iure dolorem rerum ipsa dolores nihil eveniet fuga impedit! Quae maxime ducimus tempore rem laborum iusto qui molestias, sit, possimus, doloremque veniam.
      Minima nihil deserunt corrupti et unde error ipsam dolor ab sed tempore quam esse placeat culpa quas quisquam repellat aliquam aut debitis earum quo quod nisi, assumenda in. Quis, voluptatum?
      Porro voluptatibus ea accusamus harum ipsum aliquam provident autem ex ipsam explicabo, tempora praesentium exercitationem tempore velit quod numquam asperiores sapiente sequi, officiis sint doloribus tenetur eos enim. Aliquam, dolor?
      Tenetur nam harum in quis cumque quisquam culpa, dolorum temporibus ipsa ad? Et eveniet facilis quod, atque distinctio repudiandae sequi? Praesentium, expedita! Incidunt recusandae facilis quis architecto dolor vitae asperiores!
      Id placeat cum suscipit ipsum, tenetur est nemo quibusdam voluptates illo illum sapiente accusantium modi blanditiis culpa expedita. Quaerat odio praesentium deleniti! Soluta dolor accusamus provident praesentium accusantium culpa esse.
      Est sint dolore nam sit consequuntur totam, impedit ullam repudiandae neque velit nisi quisquam fuga magni dicta mollitia odio tempora! Omnis est, soluta in doloribus esse a ipsam error nobis.
      Quae ratione debitis qui quos itaque ipsa cumque, nostrum quis perspiciatis quisquam hic nisi perferendis pariatur culpa vero sequi vel veritatis repellendus! Corrupti quis dignissimos ullam est consectetur delectus nostrum.
      Praesentium, accusantium ipsa. Iusto totam, aut soluta cupiditate modi ipsum fuga. Animi excepturi aut neque ullam nostrum repudiandae! Deserunt molestias debitis voluptatibus totam culpa commodi repellat ea repellendus, iure facere.
      In quod voluptatibus esse officiis impedit quae ea earum sed tempora aperiam! Molestiae, dolor neque! Cumque atque, aperiam neque earum minima fuga facere vero id ab explicabo porro sapiente suscipit.
      Quisquam officia doloremque consequuntur animi ipsum fugiat, pariatur voluptates dicta, aut tenetur consectetur? Est, dolorem! Consectetur cum exercitationem laborum in quod debitis omnis reprehenderit odit similique. Atque voluptates debitis esse!
      Assumenda ipsam quaerat excepturi perspiciatis, corrupti voluptate laudantium? Rem, placeat vitae? Doloremque deleniti ea, dolores cum iusto maxime sequi fugiat velit, quasi, aliquam corrupti porro esse alias necessitatibus voluptates animi.
      Voluptatem eaque consequatur vel perferendis ipsa tempora corporis error perspiciatis quaerat sapiente. Eaque rem dolores laudantium pariatur consectetur, ullam eveniet deserunt dolorum ea aperiam animi facere, similique, adipisci minus ducimus.
      Repellat, at, saepe nam consequuntur, autem blanditiis quisquam voluptatum corporis provident animi quam incidunt aliquam! Minus vel non vitae ea perferendis odio aut, consequuntur saepe dignissimos sed. Corrupti, eum quia?
      Sint asperiores perferendis provident ex non sequi cupiditate eius fugit officia eum dolorem nihil labore nobis veritatis voluptatem, dolorum et, blanditiis aperiam totam tempore cumque excepturi deleniti tenetur deserunt. Corrupti?
      A tempora et, temporibus nobis voluptas laudantium placeat maxime voluptate accusamus dolorem, quas earum repudiandae voluptates dignissimos blanditiis reprehenderit commodi dolor, deserunt alias libero obcaecati consectetur accusantium officia doloremque. Molestias.
      Sequi cumque assumenda reiciendis vel minima aspernatur consectetur possimus explicabo ducimus aliquam rerum suscipit unde est quibusdam eveniet molestiae libero eius non, ex enim praesentium, earum, magnam fugit repellendus. Cumque.
      Error ad, amet tenetur porro placeat incidunt dolorem! Ab officia ipsam pariatur eum illum nulla, asperiores sequi natus, commodi, temporibus ipsum maiores ratione? Mollitia eligendi quo quaerat eum iusto libero.
      Eum quod adipisci molestias dolorem ratione, doloribus temporibus hic. Maxime provident soluta quaerat quia, sed tempore reiciendis nam neque voluptatibus esse deserunt voluptas impedit nostrum quidem quas! Vitae, nihil officia?
      Mollitia consequuntur provident tempore sit ipsum repellat distinctio laudantium unde aliquam hic minus recusandae atque praesentium inventore nisi accusantium, sapiente dolores officiis ducimus facere repellendus itaque exercitationem expedita corrupti! Dolor?
      Ex, suscipit dolores? Provident molestiae, iste explicabo odio id maxime! Dolorum reiciendis fugiat officiis excepturi sequi cum voluptatum, beatae modi, odit sed, natus ab quos dolore provident? Iste, tempore est.
      Culpa earum ipsam ab dolorum, similique enim molestiae nobis in sapiente voluptatibus vitae mollitia expedita modi esse dolor et ex veniam, ducimus quia, nesciunt quasi animi. Tenetur consectetur maiores non.
      Tempore ratione nobis enim obcaecati officia nemo modi in cumque. Reiciendis dolor enim nisi tempore voluptatibus architecto vero labore. Accusamus earum quae saepe dolor tempore eos eveniet ullam, minus quidem?
      Ipsum quo recusandae, nisi, libero dolores repellendus, sequi quod voluptas accusamus provident autem unde blanditiis qui. Dicta nam eos autem adipisci reiciendis repellendus omnis cum porro! Doloribus quam at sint.
      Vel accusantium commodi blanditiis doloribus distinctio, consectetur dolorum libero, praesentium nesciunt ipsam tempore, itaque eum doloremque possimus corrupti perferendis fugit dicta? Tempore iure distinctio neque quas nisi aperiam autem est!
      Laudantium, perspiciatis quasi at, voluptatum quia asperiores molestiae accusamus praesentium odit dolores, aperiam corporis. Iste quisquam laudantium ipsum harum itaque doloremque, quos assumenda! Aspernatur rem hic iure, officiis corrupti quae?
      Eum tempora quia voluptas sit accusantium qui maiores quae laudantium ad minima delectus saepe corporis porro, velit repellendus dignissimos nemo tempore vero magnam non? Alias qui eveniet eum aliquam neque?
      Doloribus quis illo laborum voluptatum facere deleniti voluptates reiciendis. Cumque magni laborum tempora maiores iste possimus, quod rerum laudantium voluptatem, nihil cupiditate? Iusto fugiat, voluptatem sunt eos eius sapiente iure?
      Commodi eligendi iure inventore debitis! Blanditiis, sit ipsam! Numquam quibusdam ipsum explicabo aut reiciendis ipsa temporibus pariatur corporis odio beatae quaerat laboriosam porro in consequuntur quisquam rerum, laudantium fugit animi!
      Aspernatur recusandae quam facere accusamus! Enim possimus adipisci debitis maxime vero explicabo corrupti aliquam vel similique maiores vitae molestiae repellendus, architecto rerum quo consequatur illo dolorem dolores! Enim, facilis atque?
      Magni unde amet reprehenderit eos itaque ad vero est labore maiores voluptatem animi provident tenetur facilis quisquam ipsam voluptas nihil nam sint corporis, molestias dolores. Reprehenderit distinctio omnis deleniti pariatur!
      Temporibus pariatur nesciunt quo magni qui mollitia ex labore tempora possimus quis ipsum nisi non quas illum, amet iste sed ullam voluptate error alias. Placeat corporis natus veritatis sint dolorum.
      Neque ducimus quia architecto illum quis, eius ipsum perspiciatis officiis blanditiis a. Voluptatem hic, nisi corrupti reiciendis beatae tempore eos magni quidem incidunt repudiandae quas voluptatum itaque magnam perspiciatis id?
      Suscipit culpa exercitationem modi itaque minima corporis dolorum voluptatibus quo nihil ex facilis minus sit tenetur nostrum repellat dignissimos tempora tempore, rerum debitis animi doloribus sapiente dicta nam eaque? Odit?
      Eaque voluptate hic accusantium quia harum eligendi amet exercitationem natus debitis ipsam corporis quam, maxime quae reiciendis eius facilis laudantium saepe quo perferendis laboriosam maiores minus tenetur nostrum veritatis! Repellat.
      Quisquam voluptate alias quae ab obcaecati quod et illum doloremque delectus laborum esse numquam explicabo similique, atque eveniet dolor porro culpa laudantium, tempora ullam? Ut aliquam quibusdam vero natus quasi.
      Molestias cupiditate deleniti laborum reprehenderit veniam, eos non voluptatibus nisi officia harum, quos doloremque architecto repudiandae eius ullam aliquam vitae excepturi. Officiis rerum voluptas tempore quam a voluptate dolor nulla.
      Corrupti eum ipsum ab dignissimos porro repellendus ipsa optio, esse laudantium error, quos at consectetur. Vero corporis sint ad dolorem id, similique porro culpa consequuntur incidunt dolorum officia autem nisi.
      Illo aliquid voluptates omnis tempore velit dolorum, eius nam consequatur soluta necessitatibus obcaecati culpa nobis vitae quam eum magni officiis incidunt enim repellendus possimus sint assumenda! Nihil neque repellat vitae?
      Vero illum, fuga placeat ipsa debitis corporis enim at animi mollitia expedita laudantium, quae labore commodi recusandae deserunt officia voluptatibus odit velit maxime asperiores aliquam perferendis. Suscipit iure quidem ullam?
      Cum deleniti ratione libero repellat accusamus nemo quas fugiat corporis est debitis, quaerat nihil. Quod porro expedita aspernatur repudiandae facilis quibusdam! Esse possimus molestias quis perspiciatis nulla ratione illo expedita.
      Veritatis aperiam officia, ipsa numquam, harum quis distinctio cum quos id labore possimus dolorum optio. Officia rem dolorem, enim amet quo eos, libero, vitae velit quasi ea maxime nesciunt dolores!
      Ipsam, eligendi quia temporibus dolore eum porro iusto! Accusantium voluptate ut sunt similique quidem sit modi, repudiandae delectus placeat optio, et, earum eos dicta ex magni aspernatur! Nam, assumenda omnis?
      Accusantium itaque veniam fugiat dolore sit vel deleniti culpa facere quia! Illo eos nemo est at deleniti aperiam optio ducimus blanditiis, autem libero accusantium nisi natus sapiente, qui quia! Exercitationem!
      Atque quod dolor eaque, corporis ab aliquam temporibus impedit vel! Animi magni aliquid ad quaerat incidunt optio iusto fuga amet deserunt cumque consequuntur beatae, assumenda adipisci! Placeat dolorem cum sequi.
      Laborum, officiis ratione necessitatibus non, in eius dolor rerum blanditiis porro nesciunt exercitationem. Assumenda expedita recusandae fugiat nihil dolorem repudiandae vitae vero modi. Laborum sunt placeat sapiente corporis tempore est.
      Praesentium atque ipsa quibusdam ratione dicta suscipit, corporis obcaecati fugiat reprehenderit, mollitia nisi vel doloremque ipsum nesciunt nemo repellat non incidunt! Consectetur officia suscipit alias amet placeat blanditiis et odit!
      Tenetur odio maiores quod cum incidunt reprehenderit explicabo quo beatae voluptate, ut hic amet placeat autem! Placeat aut, tenetur sunt cum, reiciendis ex voluptatum nam omnis illum qui quaerat nisi.
      Voluptatibus quis, ipsam ipsum beatae unde quod a saepe commodi ea deleniti laborum. Exercitationem, voluptate cumque soluta a facere earum. Vel unde eum, ipsam culpa dolores placeat neque iste et.
      Sequi, ex molestias possimus quisquam quod quaerat dolores quo deleniti saepe voluptas animi assumenda eos cumque. Unde est quasi officia quis voluptates harum quod consectetur, molestiae vitae provident rem in?
      Eos quis, corrupti quasi molestias consequuntur non ullam eligendi accusamus nulla nisi nemo praesentium, est voluptas facere aliquam iste. Fuga odio enim quos harum eum, natus dolorum voluptatem! Est, et.
      Minima, quam. Ipsum exercitationem nihil quam ratione! Impedit totam, accusamus itaque cum sapiente doloremque nobis repudiandae distinctio illo quasi nihil mollitia, quidem asperiores et id eos sint ea dignissimos! Dolor!
      Ut consequuntur doloribus soluta dolor, perspiciatis quia laudantium incidunt adipisci, fuga, deleniti sit nisi. Cupiditate nesciunt placeat reprehenderit, nulla inventore aliquid quas, architecto obcaecati consectetur nam impedit dicta, laudantium optio!
      Totam explicabo blanditiis maiores laborum, animi impedit quidem eaque excepturi reprehenderit laudantium. Sunt sint neque ratione accusantium itaque error sed labore perspiciatis. Reprehenderit tempore deserunt corporis fugit asperiores dolorum nihil.
      Aspernatur saepe esse modi nulla placeat adipisci illo ut quod praesentium molestias vel eius deleniti labore necessitatibus, rem error fugiat perferendis, dolores nisi cum reprehenderit. Autem debitis optio dolores iste!
      Placeat dolorum facilis voluptates aliquam vero, fugit eaque recusandae possimus in modi excepturi odit, inventore reprehenderit delectus velit eum quasi. Hic sunt veniam laboriosam atque dicta eum voluptas ullam illum?
      Voluptatibus nostrum ipsam reprehenderit commodi autem saepe esse vel adipisci soluta optio, animi debitis culpa! Aliquam libero reprehenderit ex voluptas eveniet modi pariatur qui sapiente, optio dignissimos aut quidem consectetur!
      Quisquam hic labore corrupti similique aut ex sapiente. Minima, quis minus? Fuga nisi tempora, hic amet provident nobis a veritatis doloremque, maxime odio modi vel aspernatur, illum eum consequuntur laboriosam!
      Rerum, deserunt et earum voluptatem dolorum architecto nam eum atque quae quisquam eligendi quam consectetur voluptatibus odio labore tempora. Recusandae qui odio earum animi perspiciatis consequatur explicabo dolore odit tempora?
      Non id, totam, asperiores illum impedit veniam nesciunt nihil, libero earum hic explicabo temporibus. Commodi ex sint consectetur, maiores officia velit. Non voluptates officiis commodi dolorum quas nam soluta laudantium!
      Optio vero praesentium, asperiores numquam perferendis labore porro iure recusandae voluptate illo harum similique magnam debitis. Laborum eligendi adipisci omnis dolorum, quae ad debitis earum odit, dolores fuga officia dicta!
      Qui ea praesentium est minima, provident placeat assumenda ipsam commodi. Quod eius sunt nam sint odit, ipsa cumque. Dolor ut aut quia id laborum consequuntur in! Consequatur eaque voluptates aliquam!
      Ducimus commodi repellat rem corrupti odit asperiores nisi est dolorem voluptas facere pariatur perferendis officiis fugit, ea voluptatibus quis debitis nesciunt nemo, incidunt dolor sint, autem quae eius. Optio, cupiditate.
      Voluptatum placeat non deserunt odit eligendi dolores repudiandae magnam, inventore dolorum reiciendis doloremque. Itaque, cupiditate! Id voluptatum explicabo pariatur vitae vel, odit laudantium quam autem magni numquam similique sed cupiditate?
      Eveniet illo optio incidunt id, perspiciatis, reiciendis, velit ea tempora molestiae sunt nesciunt fugiat? Voluptas incidunt voluptate voluptatibus non, odit, neque adipisci illo hic, sed est quidem odio dignissimos maxime?
      Aspernatur maiores voluptate fuga nulla rem alias dicta! Non, tempora! Nemo, deleniti nihil quae sunt nobis pariatur beatae corrupti. Placeat officia consectetur cumque odio animi est natus omnis, ipsam id.
      Vel, optio consectetur? Laudantium illo placeat neque fugit. Veniam, odit temporibus nam eos incidunt ducimus corporis nihil saepe nostrum commodi delectus, totam, mollitia cumque aperiam fugiat. Nulla cupiditate corporis ut.
      Ipsam pariatur iusto aliquam perspiciatis cumque? Ducimus laboriosam vel nulla eaque harum eligendi minus veritatis corporis, natus neque incidunt! At vitae amet similique, eius perferendis sunt exercitationem praesentium voluptatum nam?
      Doloremque dolor aut quisquam laboriosam iste dolores recusandae, temporibus quia. Iure praesentium maxime excepturi amet saepe ab sequi itaque, hic aspernatur reprehenderit blanditiis dolor ullam ut laboriosam eligendi perspiciatis omnis.
      Accusantium asperiores, fuga facilis hic repellat eveniet maiores eius odit quasi sit beatae minus mollitia ratione tenetur, rerum laudantium architecto deserunt ut soluta assumenda! Beatae, necessitatibus? Debitis voluptates nam impedit!
      A veniam dolor est pariatur laudantium. Expedita quia aspernatur voluptatum laboriosam, saepe distinctio totam deserunt architecto nihil, ullam sed minima dolorum, tempora facere. Eum velit autem doloribus eaque ratione id?
      Incidunt iusto soluta ipsa dicta magni corporis dolorem? Maiores libero quo eum est? Alias libero obcaecati sed veritatis vel ad sint, nemo quia dignissimos? Laboriosam fugiat ullam facere libero consequatur?
      Magni sed ab commodi fuga cupiditate recusandae? Similique, illum? Optio repellat cumque dicta voluptatibus impedit, dolore blanditiis hic unde nostrum quos sunt magni eligendi ea, veritatis totam, aut porro ducimus.
      Amet obcaecati tempora repudiandae non minus voluptatum ratione consequatur expedita nihil sed libero alias distinctio, voluptate corporis veniam est odio necessitatibus eius? Fuga aliquid sapiente tempora saepe. Qui, exercitationem debitis!
      Libero eaque blanditiis maiores! Ducimus dolorum, in perspiciatis debitis dolorem, a quae distinctio nihil adipisci accusantium mollitia! Cupiditate saepe dignissimos omnis, nostrum quos quis necessitatibus hic, laudantium itaque, tempore mollitia.
      Animi rem nostrum necessitatibus molestiae magni cumque, accusamus quidem suscipit. Perferendis, ut facilis non, aperiam expedita sequi optio aliquid rerum quo, veritatis accusamus voluptatum quis earum impedit consequatur id inventore.
      Quidem nobis asperiores illo perspiciatis corrupti ab eum, optio explicabo doloribus amet esse nam culpa necessitatibus aspernatur reiciendis, dolor aliquam accusantium. Atque non alias nobis ipsa laboriosam id, architecto illo.
      Voluptas suscipit numquam quos a dolorem. Voluptatem rerum quidem iste illum, consectetur itaque! Necessitatibus doloribus eligendi praesentium excepturi reprehenderit, numquam accusantium ullam, harum eum culpa voluptatem, possimus fugit quia ad.
      Odit iusto, facilis minima doloribus iure rem! Numquam voluptas, in reiciendis perferendis officia autem corrupti doloremque non doloribus deserunt dolore dolor porro beatae animi! Dolore, cupiditate! Fugiat unde perspiciatis minus.
      Repudiandae velit, quidem nulla vel illo beatae excepturi magni ea ipsam commodi exercitationem, reprehenderit obcaecati est iusto laborum. Cumque quidem voluptatibus dignissimos libero voluptatem atque eaque a sequi praesentium dolorum?
      Nisi, ad. Doloremque accusamus quibusdam, dolore reprehenderit dicta voluptatibus saepe nihil earum distinctio inventore minus autem quia, iusto aperiam et exercitationem quo enim quaerat, error id laboriosam numquam? Labore, iusto?
      Dolores odit repudiandae laboriosam est facere, numquam explicabo nihil accusantium quam consequatur, soluta cumque corrupti, aliquam veniam. Dolor, accusantium unde. Quam deserunt voluptatum, eum quisquam distinctio blanditiis culpa perspiciatis quia!
      Obcaecati eaque ducimus reprehenderit non doloremque atque quasi pariatur adipisci enim dolorem in voluptatibus fugit officia autem, neque excepturi repellendus repudiandae esse. Dicta pariatur dolor sunt aliquid numquam exercitationem fuga.
      Reiciendis laudantium reprehenderit quis exercitationem aperiam, ipsum doloremque ex dicta dolorem, incidunt, sed maxime enim. Iure odio quis repellat! Amet alias excepturi similique? Aspernatur, et tempore tenetur rem vitae dolor!
      Eligendi aliquam exercitationem rerum autem, distinctio molestias dicta mollitia aperiam officiis nam ea voluptatum fuga. Qui, consequatur, expedita earum praesentium reiciendis labore optio corporis excepturi soluta voluptatum vero doloremque. Quaerat!
      <div className="z-10 items-center justify-between w-full max-w-5xl font-mono text-sm lg:flex my_border">
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolorem nesciunt numquam nostrum quia. Saepe praesentium omnis numquam, harum enim sed nisi exercitationem laboriosam dignissimos cumque nobis, vitae quisquam quo aliquid.
      </div>
    </main>
  );
}
